services:
  - type: web
    name: anniversary-party-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: anniversary-party-client
    buildCommand: npm install --prefix client && npm run build --prefix client
    staticPublishPath: client/dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://anniversary-party-server.onrender.com